version: '3.1'

services:
  nodejs:
    ports:
      - '80:80'
    volumes:
      - data:/usr/src/app/data

  cron:
    environment:
      - CLOUDSHELL_DOMAIN=Global
      - CLOUDSHELL_SERVER=192.168.0.110
    secrets:
      - cloudshell_password
      - cloudshell_user
    volumes:
      - cron_configs:/usr/src/script/config
      - data:/usr/src/script/data

secrets:
  cloudshell_password:
    file: dev-secrets/cloudshell_password.txt
  cloudshell_user:
    file: dev-secrets/cloudshell_user.txt

volumes:
  cron_configs:
  data: