version: '3.1'

services:
  cron:
    image: arueth/quali-utils-cron:latest
    environment:
      - CLOUDSHELL_DOMAIN=Global
      - CLOUDSHELL_SERVER=cloudshell
    extra_hosts:
      - cloudshell:192.168.0.110
    networks:
      - backend
    secrets:
      - cloudshell_password
      - cloudshell_user
    volumes:
      - cron_configs:/usr/src/script/config
      - data:/usr/src/script/data

  db:
    image: arueth/quali-utils-postgres:latest
    environment:
      - POSTGRES_PASSWORD=psql-passwd!
    networks:
      - backend
    volumes:
      - db_data:/var/lib/postgresql/data

  django:
    image: arueth/quali-utils-django:latest
    environment:
      - CLOUDSHELL_DOMAIN=Global
      - CLOUDSHELL_SERVER=cloudshell
    extra_hosts:
      - cloudshell:192.168.0.110
    networks:
      - backend
    secrets:
      - cloudshell_user
      - cloudshell_password

  nginx:
    deploy:
      restart_policy:
        condition: on-failure
        delay: 15s
    environment:
      - NGINX_SERVER_NAME=centos7-000
    image: arueth/quali-utils-nginx:latest
    networks:
      - frontend
      - backend
    ports:
      - '80:80'

  nodejs:
    image: arueth/quali-utils-nodejs:latest
    environment:
      - NODEJS_PORT=8080
    networks:
      - frontend
    secrets:
      - cloudshell_user
      - cloudshell_password
    volumes:
      - data:/usr/src/app/www/data

networks:
  backend:
  frontend:

secrets:
  cloudshell_user:
    external: true
  cloudshell_password:
    external: true

volumes:
  cron_configs:
  data:
  db_data:
